# Generated by Django 4.2.6 on 2023-10-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(blank=True, max_length=50, null=True)),
                ('nama_panggilan', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
