# Generated by Django 4.2.6 on 2023-10-11 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_tpa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jadwal', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Jadwal',
            },
        ),
        migrations.AlterModelOptions(
            name='siswa',
            options={'verbose_name_plural': 'Siswa'},
        ),
        migrations.AddField(
            model_name='siswa',
            name='alamat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siswa',
            name='kontak',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='siswa',
            name='nama_wali',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='SiswaPDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(blank=True, max_length=50, null=True)),
                ('nama_panggilan', models.CharField(blank=True, max_length=20, null=True)),
                ('nama_wali', models.CharField(blank=True, max_length=50, null=True)),
                ('kontak', models.CharField(blank=True, max_length=30, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('jadwal_mengaji', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database_tpa.jadwal')),
            ],
            options={
                'verbose_name_plural': 'Siswa PDB',
            },
        ),
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_guru', models.CharField(blank=True, max_length=30, null=True)),
                ('jadwal_mengajar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database_tpa.jadwal')),
            ],
            options={
                'verbose_name_plural': 'Guru',
            },
        ),
        migrations.AddField(
            model_name='siswa',
            name='guru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database_tpa.guru'),
        ),
        migrations.AddField(
            model_name='siswa',
            name='jadwal_mengaji',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database_tpa.jadwal'),
        ),
        migrations.AddField(
            model_name='siswa',
            name='siswa_pdb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET, to='database_tpa.siswapdb'),
        ),
    ]
