# Generated by Django 4.2.6 on 2023-10-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_tpa', '0002_jadwal_guru_siswa_guru'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='kontak',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='siswa',
            name='nama_orang_tua',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
