# Generated by Django 4.2.6 on 2023-10-10 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_tpa', '0003_siswa_kontak_siswa_nama_orang_tua'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='alamat',
            field=models.TextField(blank=True, null=True),
        ),
    ]
