# Generated by Django 4.2.6 on 2023-10-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_tpa', '0004_remove_siswapdb_keuangan_siswa_keuangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswapdb',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=20, null=True),
        ),
    ]
