# Generated by Django 4.2.6 on 2023-10-10 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_tpa', '0004_siswa_alamat'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiswaPDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(blank=True, max_length=50, null=True)),
                ('nama_panggilan', models.CharField(blank=True, max_length=20, null=True)),
                ('nama_wali', models.CharField(blank=True, max_length=50, null=True)),
                ('kontak', models.CharField(blank=True, max_length=30, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='siswa',
            old_name='nama_orang_tua',
            new_name='nama_wali',
        ),
    ]
