# Generated by Django 4.2.6 on 2023-10-11 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_tpa', '0005_siswapdb_rename_nama_orang_tua_siswa_nama_wali'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='siswa_pdb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET, to='database_tpa.siswapdb'),
        ),
    ]
