# Generated by Django 4.2.6 on 2023-10-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_tpa', '0006_siswa_jenis_kelamin'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='jilid_umi',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='siswa',
            name='spp',
            field=models.DecimalField(decimal_places=0, max_digits=30, null=True),
        ),
    ]
