# Generated by Django 4.2.6 on 2023-10-18 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_tpa', '0009_alter_siswa_jilid_umi_alter_siswa_spp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='siswa_pdb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database_tpa.siswapdb'),
        ),
    ]
