# Generated by Django 4.2.6 on 2023-10-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_tpa', '0010_alter_siswa_siswa_pdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswapdb',
            name='status_pendaftaran',
            field=models.CharField(choices=[('Sudah Terdaftar', 'Sudah Terdaftar'), ('Belum Terdaftar', 'Belum Terdaftar')], default='Belum Terdaftar', max_length=20),
        ),
    ]
